require:
  - rubocop-rails

AllCops:
  NewCops: enable

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Lint/MissingSuper:
  Enabled: false
